### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by slashtechno** [julianoappelklein/hokus#110]
Can this run on Raspberry Pi? 

I do not think there are any ARM 32-Bit releases, so if this works with Box86 (a x86 emulator) can instructions be added?

**Comment by b1nch0** [comment]
( just check main readme, you will find your desired steps
```
Building on Linux

Install the required tools:

sudo apt-get install nodejs
sudo apt-get install npm

Clone the repository and set the current directory to the root:

git clone https://github.com/julianoappelklein/hokus.git && cd hokus

Install NPM dependencies and build:

npm install && npm run dist-linux
```

**Comment by slashtechno** [comment]
> ( just check main readme, you will find your desired steps
> ```
> Building on Linux
> 
> Install the required tools:
> 
> sudo apt-get install nodejs
> sudo apt-get install npm
> 
> Clone the repository and set the current directory to the root:
> 
> git clone https://github.com/julianoappelklein/hokus.git && cd hokus
> 
> Install NPM dependencies and build:
> 
> npm install && npm run dist-linux
> ```

Sorry, I created this issue when I was less familiar with Linux, and the command line in general, and I forgot about this issue.
