### ISSUE TITLE
Feature request: Filter on selected fields

### ISSUE THREAD

**Issue by JLKM** [julianoappelklein/hokus#12]
The present filter on headlines suffice, if you're running a rather small website. But as an admin for websites bigger than say 100 documents, you need ways of grouping your material.

I haven't figured out any obvious solution, but would it in any way be possible to add more filters - f.ex. one or more filters based on values from selected fields?

Exposing the various categories or tags from the associated fields for selection without searching would be even more useful.

**Comment by julianoappelklein** [comment]
I'm still thinking about a good solution to the matter.

To filter documents by frontmatter fields, would be necessary to build some sort of index, and then add a drop-down for each available index.
Would be necessary to declare the indexes  in the collection config. A routine would ve needed to update these indexes.

This is doable, but not a small change.

Another possibility, a simpler one and not excludent with the previous one, would be to allow subfolders in a collection, making the subfolder as a category.
In content/posts/awesome/post-1/index.html, awesome would become the category, inserted in the frontmatter.
This way, a simple filter based on file path, would work.

Do you have any thoughts?

**Comment by julianoappelklein** [comment]
Ok, I agree with you. This will be my next improvement.

**Comment by julianoappelklein** [comment]
@JLKM, this feature is partially implemented. Was pushed a few days ago. I'll ping you when the version is released.
I just want to finish the GitSiteSource before launching a new version.

**Comment by julianoappelklein** [comment]
Better late then never.
Feature implemented.
