### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by w0rldart** [julianoappelklein/hokus#141]
@julianoappelklein @daniellowtw is this project now officially dead?

**Comment by mipmip** [comment]
@w0rldart you might want to checkout https://github.com/quiqr/quiqr-desktop . This is a fork of hokus, which is actively developed.

**Comment by w0rldart** [comment]
Thanks @mipmip. It would be handy to have the README updated and this repo archived in this case, to avoid further confusion
