### ISSUE TITLE
Hokus on mac

### ISSUE THREAD

**Issue by pavlunya** [julianoappelklein/hokus#18]
I managed to build hokus on my mac, but I had to install `rimraf` and `electron-builder` with `npm` globally. I don't have enough expertise to be sure that that's ok. So I need your assistance. A little bit later I'll create MR to add **mac** section to doc and `package.json`.

**Comment by pavlunya** [comment]
Well, I had not install something special, only `node` package (with [brew](https://brew.sh/)). The minimum requirements is something that I should check, because I have a lot of stuff already installed.

Basically
```
brew install node
npm install
npm run dist-mac
```

![screen shot 2018-11-22 at 3 41 15 pm](https://user-images.githubusercontent.com/2040546/48906933-b8db6780-ee6e-11e8-9d8f-7c49214dcfe5.png)

App has some glitches while scaling, but looks like it works just fine. I need a little bit more time to test.

As you can see hugo is installed. I thought It will use system installed instance, but I'm ok with that.

**Comment by julianoappelklein** [comment]
Hokus handles Hugo version by project. You have to declare the version in
the hokus.yaml file.
This way you can ensure compatibility.

About the code, push what you have. We can improve it later. Don't worry
about the details.
If something is missing, someone else can report it. Half solution is
better than none.

I'm always improving the readme file.

Looking forward for your PR.

Em qui, 22 de nov de 2018 11:59, Pavel Romanenko <notifications@github.com>
escreveu:

**Comment by vendhana** [comment]
@pavlunya - Can you please push the changes?
Have you got the icon.png with 512*512?

I packaged the app in mac using the master but facing below issue due to image size
**image /Users/XXXXX/WS/git/hokus/public/icon.png must be at least 512x512**

**Comment by julianoappelklein** [comment]
@vendhana, maybe this can help you: [Hokus CMS PNG Icon 512x512](https://user-images.githubusercontent.com/3170711/48970937-62029900-effa-11e8-8196-c5d4ce985909.png) 

I'm here to help with whatever I can.

**Comment by julianoappelklein** [comment]
Pull request merged. I'll close this one.

@pavlunya, thank you very for opening the issue. Helped a lot.
Now I'm considering to use Travis CI to build releases for all platforms regularly.

@vendhana, your PR was almost perfect. I've accepted it and after fixed the URL thing in the package.json.

**Comment by julianoappelklein** [comment]
@pavlunya, @vendhana - now we have a mac release. Thanks to you.
https://github.com/julianoappelklein/hokus/releases/tag/0.4.0
