### ISSUE TITLE
Configure Collection

### ISSUE THREAD

**Issue by yudyananda** [julianoappelklein/hokus#2]
Hi 

I have some question about how to configure collection in Hokus

**1. How do I create a list collection? for example to make tags?**
```
---
tags:
 - tag1
 - tag2
 - tag3
---
```

**2. How do I set up an image in collection?**
I mean whether there is an option to take pictures from static assets or from certain sections in the content folder. In this case I use headless bundles as folders to store image in `content/uploads/`

**3. How to make collections for nested keys?** for example
```
---
seo:
  img:
  img_alt:
  title:
  description
---

```
**4. Hokus collection has a readonly feature, but is it possible to create hidden collections that have been pre-set?**

Thank You

**Comment by julianoappelklein** [comment]
Hi @yudyananda,

To explain the adopted terminology by Hokus, the term **collection** is used to specify a group of files that share a fields configurations (like a collection of posts).

**1)** What you are asking me in 1 is how to set up fields the holds array of primitives (like tags).
Short answer: you can use the field type "chips".
But you have some more options here and, luckily, they were described in the first issue: #1 

**2)** At the moment, there isn't a resource picker to select from previously uploaded files. With a field of type **bundle-manager** you can certanily manage a collection of headles bundles. Could you share your directory structure?

**3)** You could use for your "seo" any of the following types: "nest", "section" or "pull". All of them can obtain the same data structure, but the UI is different. If you want only the UI, you can play with de property "groupdata". Both "nest" and "section" support this.
If you want only to group the data and keep a flat UI, you can use the field type "pull" (I'll probably will change this name in some version). 

**4)** Yes, there is! The field type is "hidden". Just make sure to set a "key" and a "default" value for it.

While the docs are not ready, you can use this folder as a reference for the available components:
https://github.com/julianoappelklein/hokus/tree/master/src/components/HokusForm/components

**Comment by julianoappelklein** [comment]
I think the anwser closes the issue. If you have any doubt, you know how to reach me.

**Comment by julianoappelklein** [comment]
Now is possible to see all available components in the Forms Cookbook. Look for it at the bottom left corner of Hokus UI. Just download the binaries again.

**Comment by yudyananda** [comment]
> 2) At the moment, there isn't a resource picker to select from previously uploaded files. With a field of type bundle-manager you can certanily manage a collection of headles bundles. Could you share your directory structure?

This is my content directory structure
``` bash
├───content
│   ├───authors
│   ├───blogs
│   ├───categories
│   ├───headless
│   ├───pages
│   ├───projects 
│   └───uploads #headless bundles where images and document for all content stored 
```
I'm already redownload the binnaries, cool to have more complete cookbook 👍  but still have no idea how to configure the image in the `uploads` folder. Realy get lost here, if you don't mind can You give me an example?

thank You
