### ISSUE TITLE
snap package

### ISSUE THREAD

**Issue by mdxprograms** [julianoappelklein/hokus#22]
Would it be possible to bundle this up in a snap package?

**Comment by julianoappelklein** [comment]
Hi @mdxprograms,
I don't have plans for this now. I believe we have other priorities, like a complete Git integration.
A Flatpack build is being developed (#17) and it has the same purpose.

**Comment by julianoappelklein** [comment]
@mdxprograms - the new release has a snap package. I have not tested it myself but it should work.
https://github.com/julianoappelklein/hokus/releases/tag/0.4.0
