### ISSUE TITLE
Create pages in a section

### ISSUE THREAD

**Issue by AndreKraemer** [julianoappelklein/hokus#25]
Hi, we're playing around with Hokus for some days now and we really like it. There is one thing however that we can't achieve and we don't know if its us or if it's Hokus that doesn't support the feature.

In our content folder we have a top level section called "news". What we would like to do is to create pages with Hokus in that folder. So that we get

- content/news/news-entry-1.md
- content/news/another-news-entry.md
...

What we get however is a subfolder per page:

- content/news/news-entry-1/index.md
- content/news/another-news-entry/index.md

We tried to iterate all those news Entries on our homepage using `range` but this didn't work. Any help would be appreciated.

**Comment by julianoappelklein** [comment]
Hi @AndreKraemer, 

Yes, Hokus does create by default a folder for each content page. But both ways (content/news/some.md or content/new/some/index.md) work in Hugo.

The reason I choose to wrap the markdown file in a folder is to take the benefits of [page bundles](https://gohugo.io/content-management/page-bundles/). Maybe the version you are using does not support that.

To ensure your folder content/news/ is a section, put a _index.md in it.

How are you iterating in those pages?

Have you tried to iterate over .Site.AllPages to see if it's not there?

**Comment by AndreKraemer** [comment]
Thanks for the explanation @julianoappelklein 

It turned out that we had an index.md file in the content/news folder that caused the issue.
