### ISSUE TITLE
Cannot upload images in singles

### ISSUE THREAD

**Issue by ChrisS1918** [julianoappelklein/hokus#26]
Hello Juliano,

I noticed that I cannot upload an image in singles. Is it possible to upload images in singles?
That's how I tried this:

[[singles.fields]]
title = "Upload image"
key = "bundle-manager"
type = "bundle-manager"
resourcetype = "img"
path = "/images"
extensions = [
"png"
"jpg"
"gif"
]

[[singles.fields.fields]]
key = "title"
title = "Title"
type = "string"

[[singles.fields.fields]]
key = "description"
title = "Description"
type = "string"
multiLine = true

[[singles.fields.fields]]
key = "thumb"
title = "thumbnail"
type = "bundle-image-thumbnail"

Thanks in advance.

**Comment by julianoappelklein** [comment]
Hello @ChrisS1918,

You are right, this is not implemented yet. It should not be difficult.
I'll do that if I can find some time to spare.

Thank you for mentioning it.

**Comment by julianoappelklein** [comment]
This feature is finally implemented. It will be available in the next version (0.6.0).

**Comment by goldcoders** [comment]
Ive tried using Bundle Manager , but the images key is not being populated with 
it just create a resources key in the config with content of empty array []

but the image is created inside the folder of a file...

Is there anyway we can define the path relative to the ROOT directory and not the folder where the file is located?

**Comment by julianoappelklein** [comment]
See #72
