### ISSUE TITLE
Folder files not displayed in collections

### ISSUE THREAD

**Issue by ChrisS1918** [julianoappelklein/hokus#27]
Hello Juliano,

I noticed that when I upload an image in a collections image folder that the file name is set.
But when I click into another collection and go back into the collection where I uploaded the image, the file name is not set anymore. Is there any chance to display all the image file names in the collections image folder?

Thanks in advance.

**Comment by julianoappelklein** [comment]
Hello @ChrisS1918,

I don't fully understand what is the issue here. I'll give you a brief explanation to see if we are in the same page.

A collection have many items. Like: The collection "Posts" has many posts.
Each post has it's own files. They are not shared with other posts, at least not when you are using the bundle-manager.

Also, it's important to hit the save button (bottom right) when you want the post to persist the file association.

There isn't a feature to edit shared resources yet.

Does this answer your question?

You are welcome.

**Comment by ChrisS1918** [comment]
Hey Juliano,

thank you for your answer but that's not my issue. To explain it better I'll created some screenshots.

I have a collection called "News" where I opened the news "Workshop-Kardiologie-in-Berlin".
First I'll choose an image to upload "MyImage" which works fine.

![1](https://user-images.githubusercontent.com/46931595/53323105-86159500-38dd-11e9-9629-60af5bdf0b3e.png)

![2](https://user-images.githubusercontent.com/46931595/53323125-8f9efd00-38dd-11e9-88f1-b077dd94deee.png)

Then I'll save my changes and click on the "News" collection again. For example to edit another news.
When I click on "Workshop-Kardiologie-in-Berlin" again

![3](https://user-images.githubusercontent.com/46931595/53323140-9a599200-38dd-11e9-9d02-56c385d21cbf.png)

I cannot see the previous uploaded "MyImage" (/images/MyImage.png) like in screenshot 2.

![4](https://user-images.githubusercontent.com/46931595/53323146-9fb6dc80-38dd-11e9-82cb-387fa3da009c.png)



My configuration:

[[collections]]
key = "news"
title = "News"
folder = "content/News"
extension = "md"
dataformat = "toml"
itemtitle = "Seiten"

  [[collections.fields]]
  type = "info"
  content = "# Info\nDieser Bereich dient der Erstellung von News."
  
  [[collections.fields]]
  key = "draft"
  title = "Entwurf"
  type = "boolean"

  [[collections.fields]]
  key = "pubdate"
  title = "Datum"
  type = "date"
  default = "now"

  [[collections.fields]]
  key = "type"
  title = "Typ der News"
  type = "readonly"
  default = "pages"

  [[collections.fields]]
  key = "layout"
  title = "Layout für die News"
  type = "readonly"
  default = "single"

  [[collections.fields]]
  key = "showinsitemap"
  title = "In Sitemap anzeigen"
  type = "boolean"

  [[collections.fields]]
  key = "title"
  title = "Titel der News"
  type = "string"

  [[collections.fields]]
  key = "subtitle"
  title = "Untertitel der News"
  type = "string"
  
  [[collections.fields]]
  key = "mainContent"
  title = "Inhalt"
  type = "markdown"

  [[collections.fields]]
  title="PDF hochladen:"
  key = "bundle-manager"
  type = "bundle-manager"
  resourcetype = "pdf"
  path = "/Downloads"
  extensions = [
    "pdf",
  ]

    [[collections.fields.fields]]
    key = "title"
    title = "Title"
    type = "string"

  [[collections.fields]]
  key = "leadImage"
  title = "Name des Titelbildes mit Endung"
  type = "string"

  [[collections.fields]]
  key = "footerImage"
  title = "Name des Footer-Bildes mit Endung"
  type = "string"

  [[collections.fields]]
  title = "Bild hochladen:"
  key = "bundle-manager"
  type = "bundle-manager"
  resourcetype = "img"
  path = "/images"
  extensions = [
    "png",
    "jpg",
    "gif"
  ]

    [[collections.fields.fields]]
    key = "title"
    title = "Title"
    type = "string"

    [[collections.fields.fields]]
    key = "description"
    title = "Description"
    type = "string"
    multiLine = true

    [[collections.fields.fields]]
    key = "thumb"
    title = "Thumbnail"
    type = "bundle-image-thumbnail"

**Comment by julianoappelklein** [comment]
I spotted something in your config that may be causing the issue.
You have two fields, at the same level, using the same "bundle-manager" key.

Please, let me know if that helped you.

**Comment by julianoappelklein** [comment]
Hey, try the new version. It'll validate your config files.

**Comment by julianoappelklein** [comment]
@ChrisS1918,
I assume your issue is resolved. If not, please let me know.
Cheers.
