### ISSUE TITLE
Folder files still not displayed in collections

### ISSUE THREAD

**Issue by ChrisS1918** [julianoappelklein/hokus#28]
Hello Juliano,

first sorry for my late answer.
I tried the steps you told me in the last issue.
So I installed the new Hokus version and also changed one of the two "bundle-manager" keys like the following:

[[collections]]
key = "news"
title = "News"
folder = "content/News"
extension = "md"
dataformat = "toml"
itemtitle = "Seiten"

  [[collections.fields]]
  key = "info"
  type = "info"
  content = "# Info\nDieser Bereich dient der Erstellung von News."
  
  [[collections.fields]]
  key = "draft"
  title = "Entwurf"
  type = "boolean"

  [[collections.fields]]
  key = "pubdate"
  title = "Datum"
  type = "date"
  default = "now"

  [[collections.fields]]
  key = "type"
  title = "Typ der News"
  type = "readonly"
  default = "pages"

  [[collections.fields]]
  key = "layout"
  title = "Layout für die News"
  type = "readonly"
  default = "single"

  [[collections.fields]]
  key = "showinsitemap"
  title = "In Sitemap anzeigen"
  type = "boolean"

  [[collections.fields]]
  key = "title"
  title = "Titel der News"
  type = "string"

  [[collections.fields]]
  key = "subtitle"
  title = "Untertitel der News"
  type = "string"
  
  [[collections.fields]]
  key = "mainContent"
  title = "Inhalt"
  type = "markdown"

  [[collections.fields]]
  title="PDF hochladen:"
  key = "bundle-manager-pdf"
  type = "bundle-manager"
  resourcetype = "pdf"
  path = "/Downloads"
  extensions = [
    "pdf",
  ]

    [[collections.fields.fields]]
    key = "title"
    title = "Title"
    type = "string"

  [[collections.fields]]
  key = "leadImage"
  title = "Name des Titelbildes mit Endung"
  type = "string"

  [[collections.fields]]
  key = "footerImage"
  title = "Name des Footer-Bildes mit Endung"
  type = "string"

  [[collections.fields]]
  title = "Bild hochladen:"
  key = "bundle-manager"
  type = "bundle-manager"
  resourcetype = "img"
  path = "/images"
  extensions = [
    "png",
    "jpg",
    "gif"
  ]

    [[collections.fields.fields]]
    key = "title"
    title = "Title"
    type = "string"

    [[collections.fields.fields]]
    key = "description"
    title = "Description"
    type = "string"
    multiLine = true

    [[collections.fields.fields]]
    key = "thumb"
    title = "Thumbnail"
    type = "bundle-image-thumbnail"

but the problem still remains the same.

Thanks in advance.

**Comment by julianoappelklein** [comment]
@ChrisS1918 - could you send me your full configuration file?
Don't worry, I won't share it.

You can copy & paste it here:
https://www.hokuscms.com/contact/

Thanks!

**Comment by julianoappelklein** [comment]
Hey @ChrisS1918 - found the problem.
You are using an absolute path "/Downloads" in yours bundle-manager.
Hokus is not handling this well. Use "Downloads" instead and everything will work fine.

I'll create a ticket to code a script to validate every field before letting the user use the interface.
