### ISSUE TITLE
Exceeded the "Max records limit"

### ISSUE THREAD

**Issue by ChrisS1918** [julianoappelklein/hokus#29]
Hey Juliano,

recently I updated Hokus to it's newest version but I have the following problem:
In my "News" collection I have about 150 news but Hokus told me "Max records limit reached (100)".
So it stop list my other news. Is there any possibility to increase the limit?

![limit](https://user-images.githubusercontent.com/46931595/53888028-c84c7e00-4023-11e9-8755-847eb1b1243c.png)

Thanks in advance.

**Comment by julianoappelklein** [comment]
For now, this is a hard limit.

But you can filter your collection (there is a text box at the bottom).
I put this limit to avoid rendering performance problems, but I intend to support thousands of lines in the future (but it needs a special approach, like using this library: https://github.com/bvaughn/react-virtualized ).

The filter solve your problem?

In the next version I can expose a global configuration to increase this number, while the full solution is not ready.

**Comment by ChrisS1918** [comment]
Hey Juliano,

do you mean the "Filter" textbox at the top of the collection?
If I search something I do not get any results:

![filter1](https://user-images.githubusercontent.com/46931595/53938735-6f2b2b80-40b1-11e9-9fb4-8b5d163fc83c.png)

**Comment by julianoappelklein** [comment]
I've increased the max limit to 200.
I also fixed the problem with the filter.
I'll release v0.4.1 ASAP.
Thank you for your feedback. I want more!
