### ISSUE TITLE
Examples with more exotic field types

### ISSUE THREAD

**Issue by JLKM** [julianoappelklein/hokus#3]
Took Hokus for a spin this evening. Seems perfectly suited for Hugo - but could also serve as a notetaking app. This is an awesome form-manager for markdown with plenty of use cases.

Tags and leaf-array field types work fine. Also gave some other special field types a shot - but no luck:
Error: `Cannot read property 'map' of undefined`

Would it be possible to provide some documentation and examples covering the more exotic field types like:
- accordion
- code-editor
- hidden
- nest
- readonly
- section
- select

**Comment by julianoappelklein** [comment]
Goot to hear that you are enjoying Hokus.

About the error you have mentioned, the components still lack a good error handling.
If you copy the config that triggered it, I can figure out what's happening.

About the samples, have you tried the [Hokus Forms Cookbook](http://formscookbook.hokus.io.s3-website-us-east-1.amazonaws.com/)? It has at least one sample for each relevant component.

**Comment by JLKM** [comment]
Ups. Missed that cookbook in the first place. Have tested the main part of the components, and they work fine. Even after converted to yaml. Awesome.
