### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by ct-martin** [julianoappelklein/hokus#33]
Right now Hokus' README states "Free for commercial use". However, Hokus does not have a license that defines this in any easily discernible place (such as a LICENSE file or `package.json`). Not having a license also means that potential contributors don't have a right to modify nor release modifications to your code, and thus theoretically can't make Pull Requests (*: I am not a lawyer). Since your "Help Wanted" section of the README is encouraging contributors, I can safely assume this isn't your intent. Hokus looks like it's a good project and it'd be nice to have a license that allows others to safely use, share, and modify it.

GitHub has a nice website explaining licenses (or lack thereof) and what they mean: https://choosealicense.com/

**Comment by rpetit3** [comment]
Submitted https://github.com/julianoappelklein/hokus/pull/35
