### ISSUE TITLE
Cannot change the version of Hugo within Hokus

### ISSUE THREAD

**Issue by AgileWish** [julianoappelklein/hokus#34]
I tried changing the Hugo version inside of the tool.  It did not allow me to change it.

Current version when I did the fresh install.
Hugo installation started. Downloading package from https://github.com/gohugoio/hugo/releases/download/v0.50/hugo_0.50_macOS-64bit.tar.gz...
Unpacking....
Hugo installation completed.
Starting Hugo Server..

When I try to do the same by changing the hokus.toml file changing it to 0.58 then I get the following error.  Is there a way to run it with newer version of Hugo?

Hugo Server Closed: 255
Hugo installation started. Downloading package from https://github.com/gohugoio/hugo/releases/download/v0.58/hugo_0.58_macOS-64bit.tar.gz...
Unpacking....
Hugo installation failed.

**Comment by AgileWish** [comment]
I figured out the difference.  I had to specify the version as 0.58.1.  It worked after that.

**Comment by julianoappelklein** [comment]
@AgileWish - yes, the version name must match the GitHub releases page:

https://github.com/gohugoio/hugo/releases
