### ISSUE TITLE
Feature request: Multi-value select

### ISSUE THREAD

**Issue by JLKM** [julianoappelklein/hokus#6]
Chips works fine. Select the same. How about a multi-value select component?

**Comment by julianoappelklein** [comment]
Ooops.. It's really missing.
I'll add the feature in the next release.

For now, there is a work around: Use a leaf-array combined with a select.

You'll have the same data contract and the same values enforcement.

I'll keep the issue open until next release.

And thanks for point this out.

**Comment by JLKM** [comment]
Thank you. I'll look forward to next release.

**Comment by julianoappelklein** [comment]
Hey @JLKM, the new version is out.

To make a multi-select, just add a multiple=true to the field.

I also added a sample in the Forms Cookbook (included in the application, accessible in the bottom left menu).

I'm looking forward for your feedback.

**Comment by JLKM** [comment]
`select-multiple` works like a charm. Not able to conceive more field-types, that your components don't cover allready...

**Comment by julianoappelklein** [comment]
Good to hear this @JLKM!

The next move is to add validations to current field types (like required, maxLength, maxItemsLength, minItemsLength, pattern, maxValue, minValue, and so on).

And fields are not only about handling data. Hokus needs, for example, a good WYSYWYG component. Markdown is nice, but not to everyone.

But I think we already have a good set for the moment.

Don't you miss something? What do you think?
