### ISSUE TITLE
[0.6.0 Appimage] Error /home/[username]/Hokus does not exist.

### ISSUE THREAD

**Issue by timhughes** [julianoappelklein/hokus#60]
Minor bug with the Appimage release. 
![Screenshot from 2020-05-12 15-55-38](https://user-images.githubusercontent.com/1203343/81709001-84e07180-9469-11ea-84ac-da76d7fd3c9a.png)

If I create the directory by hand then Hokus starts ok.

**Comment by julianoappelklein** [comment]
Hello @timhughes, thank you for reporting the issue.
I published v0.6.1 to fix it.
