### ISSUE TITLE
Selecting a site with gitsource gives sometimes an Unhandled Promies Rejection

### ISSUE THREAD

**Issue by AndreKraemer** [julianoappelklein/hokus#62]
When selecting a site from the main menu after closing it before, we sometimes get a Unhandled Promise Rejection. It looks like there is still a git process running in this git repository. 

![2020-05-13_11h48_47](https://user-images.githubusercontent.com/312671/82024440-16c9c380-9690-11ea-81ab-a48b50356e25.png)

**Comment by julianoappelklein** [comment]
Yes, it makes sense. Some processes, like git fetch run regularly, locking the repository.

I added some extra checks before doing some git commands. Now some processes can wait for one second until a process is unlocked before executing a git command. If the lock is not released in one second, the process will fail silently.

This will be released in next version, v0.6.2.

**Comment by julianoappelklein** [comment]
Issue fixed in v0.6.2.
