### ISSUE TITLE
How to define in main config an array in a toml file

### ISSUE THREAD

**Issue by goldcoders** [julianoappelklein/hokus#66]
I have a big config.toml file 

but the main config preset has only title, baseurl , theme, languagecode , google analytics and enableRobots as example.

I do have a menu footer which is an array
how do i define it on the UI
what key do i foot , does menu.footer works?

Im kinda confuse since there is very small details on the documentations

can you help me thanks

**Comment by julianoappelklein** [comment]
I'm releasing a new version that provides a UI to edit configurations.

Sorry about the documentation. It's hard to find time to code and create docs.

Maybe you could help me!

**Comment by goldcoders** [comment]
Ive sent you an email please check
