### ISSUE TITLE
Hugo Server Error

### ISSUE THREAD

**Issue by goldcoders** [julianoappelklein/hokus#67]
hi Im getting this error ,

<details>
<summary>error</summary>

```sh
This is the application output console. Here you can learn about what is happening behind the scenes.

Starting Hugo Server...

Hugo Server Error: Error: Error building site: POSTCSS: failed to transform "css/styles.css" (text/css): resource "css/css/styles.css_2470d520f8390e01a1a99d32c19f09b5" not found in file cache

Hugo Server Closed: 255
```

</details>

would love to know what hugo command is being run when you click play button then default...

This error is happening since my local version which i pulled from remove already uses the production build

So the css being used is incorrect since production build != dev  when running the hokus cms

It will be cumbersome for non dev user when they face this...

me i can easily run hugo server and the errors go away after i quit that instance since...

the resources of css being used is for development...

Is there a way i can define what command to run when user click play then default ... ??

**Comment by goldcoders** [comment]
all i can see in the Hokus/config.demo.json is this

```json
{
  "key": "demo",
  "name": "demo",
  "source": {
    "type": "folder",
    "path": "/home/user/.hugo/demo"
  },
  "publish": [
    {
      "key": "default",
      "config": {
        "type": "folder",
        "path": null
      }
    }
  ]
}

```

maybe we can improved this by reading on netlify.toml file if you have it...

its pretty straight forward to have a command like this being set on hokus config json file

```
[build]
  publish = "public"
  functions = "netlify-lambda"
  command = "hugo --gc --minify && npm run build"

[dev]
command = "hugo server --disableFastRender"
autoLaunch = true
```

**Comment by goldcoders** [comment]
I see there is this serve and build in hokus.toml

```toml
"serve":[
    {
      "key":"default",
      "config":"config.toml",
      "command": "hugo server --disableFastrender --ignoreCache" // maybe we can add this command???
    }
  ],
  "build":[
    {
      "key":"default",
      "config":"config.toml"
    }
  ],
```

Hope we can make this more flexible to define the command we want to run....

**Comment by julianoappelklein** [comment]
This sounds good to me.
We just need to extend the serve config in hokus.yaml.

But we already have a degree of flexibility now. I think it solves your problem. As you can see we can register many serve and build configurations.
And in a serve config we can set the config file, we can even use many config files. The first have precedence over the later.  Hugo config files support flags like disableFastrender and ignoreCache.
```
"serve":[
    {
      "key":"default",
      "config":"config.yaml,config-dev.yaml",
      "command": "hugo server --disableFastrender --ignoreCache" // maybe we can add this command???
    }
  ],
```
and the config-dev.yaml could be something like:
```
disableFastRender: true
disableCache: true
```

But about your suggestion of extending the configuration to make it simpler, how about this:

```
"serve":[
    {
      "key":"default",
      "config":"config.toml",
      "params": ["--disableFastrender" "--ignoreCache"] OR "--disableFastRender --ignoreCache"
    }
  ],
```

Let me know what do you think.

**Comment by goldcoders** [comment]
there are different use cases we can use the params to advantage...

what i see it will failed most of the time is when using the theme itself as the main site...

I do have hugo site that is serve as a theme...

so adding a way to modify params 

```
hugo server -s exampleSite --themesDir=../.. --theme=hugo-theme-twal-starter
```

do u think its better if we just override the command or push the params...

modifying the command is easier ....

if no command is define we can fallback to the default hugo serve and hugo --gc --minify (production)

**Comment by julianoappelklein** [comment]
Yes, for this use case I think would be better to have a way to write custom command line commands.
I would just replace the hugo for something else, maybe a environment variables ($hugo), because Hokus manages the Hugo version being used for every build.

**Comment by goldcoders** [comment]
hugo will still remain there , cause it will still be called underhood  for example by netlify dev ....
netlify dev can be included as a dev dependencies on a project,
and we can just reference the command inside node_modules/

this is good assuming hokus knows to download all the dev dependencies when creating a new site
does hokus download all the npm  dependencies by default with folder type site or only in git source type?

**Comment by julianoappelklein** [comment]
> this is good assuming hokus knows to download all the dev dependencies when creating a new site
> does hokus download all the npm dependencies by default with folder type site or only in git source type?

I would go for custom scripts to handle that.
Initialize, serve, build, deploy.
