### ISSUE TITLE
Does Hokus cms pull all the npm dependencies?

### ISSUE THREAD

**Issue by goldcoders** [julianoappelklein/hokus#68]
We are assuming that people that will use hokus cms dont know a thing about NPM
or installing its dependencies, they will just download  zip file extract it ...
Install hokus and create new site pick folder then voila... site is up and running...
is there a portion in hokus where in you instruct hokus to fetch all npm dependencies if no node_modules folder is found?

**Comment by julianoappelklein** [comment]
Node is not required.
Currently, Hokus bundles everything with it. Except Git.
