### ISSUE TITLE
 Sync Button not working

### ISSUE THREAD

**Issue by goldcoders** [julianoappelklein/hokus#70]
I created a new site
filled up key
source type : folder
pick folder (which is a git repo i have locally)
theme repository url is blank 

this first site is a hugo site not a theme...

I created a second site
source type: folder
pick folder
set theme repository url

Starting Server works fine also the publish buttons works fine 

and it created a 2 new site folder in ~/Hokus/sites/

and each site has build and publish folder...

The difference in the 2 site 
first one is litterally a hugo site and is a git repo locally

the theme site when created is not a git repo locally

Now the question is why on the first site SYNC button is not working...

it should be doing syncing right when that button is clicked?

or is that button only working on git source type...

so i tried now git source type

but since my hugo set up is kinda complex 

i do have have error immediately when starting server

I think we need to bundle also GO right besides hugo bin

```
Hugo Server Error: Error: we found a go.mod file in your project, but you need to install Go to use it. See https://golang.org/dl/.: module "github.com/bep/hugo-jslibs/turbolinks" not found; either add it as a Hugo Module or store it in "/home/uriah/Hokus/sites/thriftshop-site/workspaces/master/themes".: module does not exist

```
so for now i did installed the dependecies of hugo
 by running hugo mod get

second error now appears 

```
Hugo Server Error: Error: we found a go.mod file in your project, but you need to install Go to use it. See https://golang.org/dl/.: module "github.com/bep/hugo-jslibs/turbolinks" not found; either add it as a Hugo Module or store it in "/home/uriah/Hokus/sites/thriftshop-site/workspaces/master/themes".: module does not exist
```
this error is related to private git repo , and recursive repository dependencies

i guess we need a way to tell hokus to use command

git clone --recursive 

but anyway...

no solution on that yet, so i bailed out

but surprisingly when i edit on this third site a site config and click sync it work and made a push on my master repo...

fourth try , i tried to modify the first site config inside hokus folder

```
"key": "tss",
  "name": "tss",
  "source": {
    "type": "folder",
    "path": "/home/user/.goldcoders/tss",
    "url": "https://password@github.com/user/REPO.git",
    "autosync": false
  },
```
sync button is not working, my realization on this is the folder structure is not the same when creating a git source vs the normal folder source repo...

it would be great if you can help me make SYNC button work...

**Comment by julianoappelklein** [comment]
The sync button should not be available for sites with Source Type Folder, you found a bug :)

About the go dependency, I don't have GO installed.

**Comment by goldcoders** [comment]
well, about fetching hugo modules that needs go binary ...

i can remove it on .gitignore, for now and just include it on the git repo...

Well I just found out that git source type...

can only live on ~/Hokus/sites/SITENAME/

and on that folder it has 3 subfolder that will be created

- build
- publish
- workspace

I did find a way to make the SYNC button work with my set up...

but it involves me moving the WHOLEREPO folder inside `~/Hokus/sites/SITENAME/workspace/master`

and later on just created a symbolic link to the WHOLEREPO and just point it on master

ok now hear my suggestion

folder source type should adhere to same as git source type...

the solution im thinking is what i did above by using symlink on linux/mac and shorcut on windows

a folder source type would use the same folder structure like the git source

they should both live under ~/Hokus/sites and just make a symlink or shortcut on SITENAME/workspace/master

but the current git source type now , the workspace folder is a REPO and the workspace/master is another repo.

its a bit cumbersome to have a cloned repo then having a folder master that has same content...

Is there a reason for it? i read a post here about git source type having multiple branches...

i think just using workspace/master directly is better rather than having 2 cloned repo 

one on workspace and another one on workspace/master... workspace/branch...

and just ommit the workspace REPO itself, it should only contain the branches folder 

secondly Ive just noticed that when using git source type...

NPM dependencies are not installed...

same goes for hugo modules , GO dependencies...

I think we can add that to BIN folder like hugo-bin that is also versioned?

I think we can get the released on node and npm and so as Go on their official pages....

What do you think of this?

**Comment by julianoappelklein** [comment]
Well, this is what I think.

The ideia behind having different site sources is to have different workflows.
I intend to remove the sync button - it does not work on sites using Folder Source.

We need to improve the Git Site Source and keep the Folder Site Source as simple as possible.
I use one folder per branch because this way the user can switch between branches without worrying about "git stash".
And eventually - if the project go in this direction - a user could have two instances of the project in different versions.

What you really need is a way to handle custom scripts to initialize a workspace, build/server/deploy. And to have this, the user must check a checkbox allowing the execution of custom scripts. We can't bundle everything with Hokus because this will bring other problems and challenges that we'll not be able to handle.

We can also create some sort of hokus.readme.md, so the developer can create instructions to install the dependencies we can't handle automatically.

We need to keep it simple. We need to avoid bringing more responsibilities to Hokus.

Does this make sense to you?

**Comment by goldcoders** [comment]
You said ,`I intend to remove the sync button` - it does not work on sites using Folder Source.

Can you pin point me the function it is calling , and the script it is running...

Maybe I can make a pull request and fix that ...

Folder Source can be fix by using the same folder structure and config of git Source...

Then Use Symlink or in windows shortcut link....

We can make the Creating of New Site more verbose if you want...

Hugo Has many site complexity , and Mine is already using a complex one....

Since You Already add the Idea of hugo-bin, maybe we can make a bin folder that holds all the folder for each executable

like NODE ,GO, NETLIFY CLI which During  Creating new Site...

Will be detected if there is a package.json or hugo.mod or netlify.toml

If the system cant detect it, but the developer know what executable he needs

maybe we can add URL to download release of specfic version.

or better yet add it on hokus.toml file we can define list of executables with version and url that needs to be downloaded...

then add custom command to run depending if we are dev, build or deploy...
